#!/usr/bin/env bash
# run covid-19 files 
# git add, comit and push

# launchd is built into macOS and is an alternative to linux's cron
# .plist for launchd is at ~/Library/LaunchAgents/coinmarketcap_scanner.plist

# $ launchctl list | grep coinmarketcap_scanner
#  0  coinmarketcap_scanner

# test/debug 
# $ launchctl start coinmarketcap_scanner

# if you need to stop
# $ launchctl stop coinmarketcap_scanner


### When do you need to run these?
# load the job
# $ launchctl load /Users/daniel/Library/LaunchAgents/coinmarketcap_scanner.plist

# unload the job
# $ launchctl unload /Users/daniel/Library/LaunchAgents/coinmarketcap_scanner.plist

# get help
# $ launchctl help


# https://towardsdatascience.com/a-step-by-step-guide-to-scheduling-tasks-for-your-data-science-project-d7df4531fc41#bfcb
# Papermill is a tool for parameterizing and executing Jupyter Notebooks. I can use this to run a Jupyter Notebook file in a cron or launchd job file.
# Install in current python environment with `pip3 install papermill`
# papermill --help

# terminal-notifier is a command-line tool to send macOS User Notifications. I will use this to notify me when the scheduled job is done.
# brew install terminal-notifier
# terminal-notifier -help


# If you run into issues, make sure your pfile is good with - plutil (ships with MacOS)
# Other docs: https://www.wrighters.io/parameters-jupyter-notebooks-with-papermill/


cd "$(dirname "${BASH_SOURCE[0]}")"
pyenv activate venv_coinmarketcap_scanner # Not necessary if iwe are calling this bash script from within this folder
papermill coinmarketcap_scanner.ipynb ./output/output.ipynb
git add . 
git commit -m "update" 
git push
terminal-notifier -title "Coin Market Cap Scanner" -subtitle "Daily Update" -message "Completed"
now=$(date)
echo "launchd update completed at $now"